### ISSUE TITLE
Pip install is not taking poetry.lock file into consideration

### ISSUE THREAD

**Issue by MartinWallgren** [bmaingret/coach-planner#4]
I suggest generating a constratins.txt file during the build stage.

`RUN poetry export --without-hashes > constraints.txt`

And using that constraints file when installing the wheel.

`RUN pip install ./$APP_NAME*.whl -c constraints.txt`

The generated wheel will have the open ended version from pyproject.toml for all dependencies.
Using a constraints file for pip install will ensure that all dependencies get the exact same version as defined in poetry.lock.

**Comment by bmaingret** [comment]
Thanks for the suggestion. This has been implemented.
